@startuml
title 状態管理クラス

class "StateManager" as ClassStateManager{
  -currentState : SystemStatus
  -{static}temperatureGetter : TemperatureGetter
  -{static}temperatureControler : TemperatureControler
  -{static}const TEMPERATURE_LOWER_LIMIT = 27 : float_t
  -{static}const TEMPERATURE_UPPER_LIMIT = 28 : float_t
  +manageRoutine() : void
  -calcurateNextState(currentTemperature : float_t) : SystemStatus
}
enum "SystemStatus" as EnumSystemStatus{
  HEATING
  KEEPING
  COOLING
}

ClassStateManager "0..*" *-- "1" EnumSystemStatus
@enduml
