@startuml
title 状態管理クラス

class "StateManager" as ClassStateManager{
  -currentState : SystemStatus
  +startManaging() : void
  +manageRoutine() : void
  +stopManaging() : void
  -calcurateNextState() : SystemStatus
}
enum "SystemStatus" as EnumSystemStatus{
  HEATING
  KEEPING
  COOLING
}
@enduml
